SERVER_HOST = "0.0.0.0"
SERVER_PORT = "8000"
DEBUG = True
MAX_CONTENT_LENGTH = 2 * 1024 * 1024
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://user:password@127.0.0.1/sample?charset=utf8mb4"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
SQLALCHEMY_EENCODING = "utf-8"
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_MAX_OVERFLOW = 0
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/1"

MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_SERVER = "smtp-server"
MAIL_USERNAME = "username"
MAIL_PASSWORD = "password"
MAIL_DEFAULT_SENDER = "sender-name"
